# NUMPY 
#### INTRODUCTION

NumPy (Numerical Python) is a powerful Python library for numerical computations. It provides support for multi-dimensional arrays (ndarrays) and a wide range of mathematical functions to operate on them efficiently. NumPy is essential for scientific computing, data analysis, and machine learning due to its speed and versatility.

## LIBRARY INSTALLATION

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## IMPORT THE LIBRARY

In [3]:
import numpy as np

- ### what is an array?
 An array is a central data structure called an ndarray (N-dimensional array). It is a grid of elements (usually numbers) of the same data type, organized in a multi-dimensional structure. Arrays are more efficient than Python lists for numerical operations because they are stored in contiguous memory and support vectorized operations. For example, a 1D array is like a list, while a 2D array can represent a matrix. NumPy arrays enable fast computations and are the foundation for many scientific and data analysis tasks.


![download.png](attachment:download.png) 
![download (1).png](<attachment:download (1).png>)

#### ONE DIMENSIONAL

In [4]:
#for example
a=np.arange(6) # it is one dimensional
a

array([0, 1, 2, 3, 4, 5])

##### SHAPE

In [5]:
a.shape #tell us that have 6 colom and 1 rows


(6,)

#### TWO DIMENSIONAL

In [6]:
a2= a[np.newaxis, :] # it is two dimensional array
a2

array([[0, 1, 2, 3, 4, 5]])

##### SHAPE


In [7]:
a2.shape #tell us that have 6 colom and 1 rows


(1, 6)

#### THREE DIMENSIONAL

In [8]:
a3= a[np.newaxis, : ] # it is two dimensional array
a3

array([[0, 1, 2, 3, 4, 5]])

In [9]:
a3.shape #tell us that have 6 colom and 1 rows


(1, 6)

In [10]:
a.shape #tell us only colum means only 6

(6,)

### ***WHY DO WE HAVE 1D,2D AND 3D ARRAYS AND WHERE WE NEED HEM IN DATA SCIENCE ?***
***Efficient Data Representation:***

Real-world data is often multi-dimensional (e.g., images, videos, sensor data).

Arrays provide a structured way to store and process such data.

***Mathematical Operations:***

Arrays enable vectorized operations, which are faster and more efficient than loops.

Essential for linear algebra, statistics, and machine learning algorithms.

***Compatibility with Libraries:***

Most data science libraries (e.g., Pandas, Scikit-learn, TensorFlow) use NumPy arrays as input.

***Handling Complex Data:***

1D for simple lists, 2D for tables, and 3D+ for advanced data like images or videos

#### FOR EXAMPLE
1D Array: A list of house prices.

2D Array: A dataset of houses with features like size, bedrooms, and price.

3D Array: A set of RGB images for a computer vision task.

---

## CREATING ARRAYS WITH NUMPY

In [11]:
a= np.array([1,2,3,4,5,6])
b=np.array([(1,2,3,4,5,6),(4,5,6,7,8,9)])

In [12]:
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [13]:
print(b)
b.shape

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


(2, 6)

### INITILIZE ARRAYS

- ZEROES

In [14]:
zeros =np.zeros((3,4))  #(rows,coloums)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
zeros =np.zeros((4,4))  #(rows,coloums)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
zeros =np.zeros((6,9))  #(rows,coloums)
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

- ONES

In [17]:
ones =np.ones((6,9))  #(rows,coloums)
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
ones =np.ones((3,9))  #(rows,coloums)
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

- FULL

In [19]:
full =np.full((2,5),3)
full

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [20]:
full =np.full((2,5),6)
full

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [21]:
full =np.full((2,5),2)
full

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

 - EMPTY

 
 Empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [22]:
empty = np.empty((2,3))
print(empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23043429e-307 2.22526399e-307 2.05837348e-312]]


In [39]:
empty = np.empty((1,2,3))
print(empty)

[[[4.9e-324 9.9e-324 1.5e-323]
  [2.0e-323 2.5e-323 3.0e-323]]]


In [40]:
empty = np.empty((3,2,3))
print(empty)

[[[1.37962049e-306 1.24610791e-306 1.27452217e-311]
  [1.27452217e-311 1.27454051e-311 1.27452217e-311]]

 [[1.27452217e-311 1.27452217e-311 1.27452217e-311]
  [1.27452217e-311 1.27452217e-311 1.27452408e-311]]

 [[1.27452217e-311 1.27453526e-311 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]]


- ARANGE

We can create an array with a range of elements

In [41]:
x= np.arange(4)
# Create a 2D array with the specified shape
x

array([0, 1, 2, 3])

In [42]:
y=np.arange(2, 9, 2) # will specify the first number, last number, and the step size.
y

array([2, 4, 6, 8])

In [44]:
z=np.arange(2, 100, 10)
z

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

- LINESPACE

create an array with values that are spaced linearly in a specified interval

In [ ]:
g=np.linspace(0, 10, num=5)
g

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
g=np.linspace(0, 10, num=5)

In [46]:
g=np.linspace(0, 10, num=2)
g

array([ 0., 10.])

In [47]:
h=np.linspace(0, 10, num=50)
h


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

---

### MATRIX

- IDENTITY MARIX

In [23]:
identity=np.eye(3)   #.eye help us tto create an identitiy matrix
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### TO CHECK DATA TYPES

- DTYPE WILL LET US KNOW THE TYPE OF ARRAY ELEMENTS

In [24]:
# BOTH HAVE SAME DATA TYPES
a= np.array([1,2,3,4,5,6])
a.dtype
b=np.array([(1,2,3,4,5,6),(4,5,6,7,8,9)])
b.dtype

dtype('int64')

In [25]:
ones =np.ones((3,9))  #(rows,coloums)
ones.dtype

dtype('float64')

In [26]:
zeros =np.zeros((6,9))  #(rows,coloums)
zeros.dtype

dtype('float64')

In [27]:
full =np.full((2,5),2)
full.dtype

dtype('int64')

In [28]:
full =np.full((2,5),2.6)
full.dtype

dtype('float64')

In [29]:
identity=np.eye(3)   
identity.dtype

dtype('float64')

### TYPE OF ARRAY

- LET US THE TYPE OF ARRAY LIKE WHAT TYPES OF THE WHOLE ARRAY IT IS ABOUT

In [30]:
a= np.array([1,2,3,4,5,6])
type(a)

numpy.ndarray

In [31]:
ones =np.ones((3,9))  #(rows,coloums)
type(ones)

numpy.ndarray

---

## ARRAY ARTRIBUTES

- ### 1. SHAPE

In [32]:
a= np.array([1,2,3,4,5,6])
a.shape

(6,)

In [33]:
ones =np.ones((3,9)) 
ones.shape

(3, 9)

In [34]:
full =np.full((2,5),2)
full.shape

(2, 5)

- ### 2. length


In [35]:
a= np.array([1,2,3,4,5,6])
len(a)

6

In [36]:
full =np.full((2,5),2)
len(full)

2

In [37]:
ones =np.ones((3,9))  #(rows,coloums)
len(ones)

3

- ### 3. NDIM(FOR DIMENSION)

In [38]:
a= np.array([1,2,3,4,5,6])
ndim(a)

NameError: name 'ndim' is not defined

- ### 4. SIZE
TELL US THE SIZE MEANS NO OF ELEMENTS IN ARRAYS

In [ ]:
full =np.full((2,5),2)
full.size

10

In [ ]:
ones =np.ones((3,9)) 
ones.size

27

---

## BASIC OPERATIONS

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
b

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

### SUBTRACTION

In [ ]:
g = a-b
g

array([[ 0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3]])

In [ ]:
g = b-a
g

array([[0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3]])

### ADDITION

In [ ]:
h = a+b
h

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

In [ ]:
h= b+a
h

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

##### WE CAN ALSO ADD BY USING .ADD

In [ ]:
h1 = np.add(a,b)
h1

array([[ 2,  4,  6,  8, 10, 12],
       [ 5,  7,  9, 11, 13, 15]])

### MULTIPLICATION

In [ ]:
a*b


array([[ 1,  4,  9, 16, 25, 36],
       [ 4, 10, 18, 28, 40, 54]])

### DIVISION

In [ ]:
a/b

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667]])

### SQUARE

In [ ]:
i = a**2
i

array([ 1,  4,  9, 16, 25, 36])

In [ ]:
k = b**2
k

array([[ 1,  4,  9, 16, 25, 36],
       [16, 25, 36, 49, 64, 81]])

---

# SORT AND CONCATENATION

### SORT

FOR SORT WE ARE GONNA USE .SORT

In [50]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
arr1 = np.array([5,9,8,7,6,4,2,3,1,5,9,8,10,25,32,15,47,58,59,41,15,12,11])
arr1.sort()
arr1

array([ 1,  2,  3,  4,  5,  5,  6,  7,  8,  8,  9,  9, 10, 11, 12, 15, 15,
       25, 32, 41, 47, 58, 59])

In [52]:
arr2 = np.array([2, 1, 5, 3, 7, 4, 6, 8,21,54,87,89,56,23,25,26,27,98,74,11])
arr2.sort()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8, 11, 21, 23, 25, 26, 27, 54, 56, 74,
       87, 89, 98])

### CONCATENATION

Concatenation is the process of joining two or more strings together to form a new string. In
 you can use the `+` operator to concatenate strings.


In [54]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
x1 = np.array([[1, 2], [3, 4]])
y1= np.array([[5, 6],[3, 4]])
np.concatenate((x1, y1),axis=1) # AXIS IS USED 1 WHEN BOTH ARRAY HAVE SAME COLOUMS AND ROWS MEANS 2*2 OR 4*4

array([[1, 2, 5, 6],
       [3, 4, 3, 4]])

---

# 3-D ARRAYS

In [63]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example
                           

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [64]:
array_example.size

24

In [65]:
array_example.shape

(3, 2, 4)

In [66]:
array_example.dtype

dtype('int64')

In [67]:
array_example.ndim

3

---

# RESHAPE OF THE ARRAYS

In [68]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


You can use reshape() to reshape your array. For example, you can reshape this array to an array with three rows and two columns

In [69]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [70]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


---

# How to convert a 1D array into a 2D array

We can use np.newaxis and np.expand_dims to increase the dimensions of your existing array

### NP.NEWAXIS

In [71]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [72]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

You can explicitly convert a 1D array to either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension

In [73]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

OR FOR COLOUM

In [74]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

### NP.EXPANDDMIS

WE can use np.expand_dims to add an axis at index position 1 with

In [75]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [76]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

We can add an axis at index position 0 with

In [77]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

---

# INDEXING AND SLICING

We can index and slice NumPy arrays in the same ways you can slice Python lists.



In [78]:
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

#### DATA

In [83]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.



In [79]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array

In [80]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


You can select elements that are divisible by 2

In [81]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the & and | operators



In [82]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


For return boolean values that specify whether or not the values in an array fulfill a certain condition

In [84]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
